# creates service account with permissions to access prometheus metrics
kind: ServiceAccount
apiVersion: v1
metadata:
  name: genie-obs-mcp-thanos-querier
  namespace: openshift-lightspeed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: genie-obs-mcp:system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: genie-obs-mcp-thanos-querier
    namespace: openshift-lightspeed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: genie-obs-mcp
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - monitoring.coreos.com
    resourceNames:
      - k8s
    resources:
      - prometheuses/api
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - "config.openshift.io"
    resources:
      - consoles
    verbs:
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: genie-obs-mcp-thanos-querier
subjects:
  - kind: ServiceAccount
    name: genie-obs-mcp-thanos-querier
    namespace: openshift-lightspeed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: genie-obs-mcp
